/**
 * Phase 2 measurement gate (04 §4).
 *
 * `scripts/baseline-new.sh` must assemble the SAME fixture KB as
 * `scripts/baseline-old.sh` — one `node apply` instead of 21 `node create`s, three
 * batch `synthesize`s instead of 21 single ones — for at most HALF the command count,
 * and it must gather every synthesis input through `node show --context` rather than
 * by hand-assembling context from bare reads.
 *
 * Equivalence is asserted on `scripts/kb-snapshot.ts` output — the normalized semantic
 * snapshot. Raw DB bytes are *expected* to differ (timestamps, changelog, ids of a
 * different write order); meaning is not.
 *
 * The scripts are slow (they drive the real CLI 22 and 54 times), so both run once in a
 * file-level `beforeAll` and every assertion reads those results. The same run also
 * pins `docs/plans/baseline.md`: it is generated by `scripts/gen-baseline.sh`, so a
 * change to either assembly path that is not re-recorded fails here.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(import.meta.url), '../../..');
const OLD_SCRIPT = join(ROOT, 'scripts/baseline-old.sh');
const NEW_SCRIPT = join(ROOT, 'scripts/baseline-new.sh');
const BASELINE_MD = join(ROOT, 'docs/plans/baseline.md');

interface Assembly {
  kbDir: string;
  commands: number;
  snapshot: string;
}

/** Run a baseline script into a fresh temp KB and capture its count + semantic snapshot. */
function assemble(script: string, label: string): Assembly {
  const kbDir = mkdtempSync(join(tmpdir(), `kb-baseline-${label}-`));
  const out = execFileSync('bash', [script, kbDir], { cwd: ROOT, encoding: 'utf8' });
  const m = /^COMMANDS=(\d+)$/m.exec(out);
  if (!m) throw new Error(`no COMMANDS= line in output of ${script}:\n${out}`);
  const snapshot = execFileSync(join(ROOT, 'node_modules/.bin/tsx'), [join(ROOT, 'scripts/kb-snapshot.ts'), kbDir], {
    cwd: ROOT,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  return { kbDir, commands: Number(m[1]), snapshot };
}

/** The single `COMMANDS(<which>) = <n>` figure recorded in docs/plans/baseline.md. */
function recordedCount(md: string, which: 'old' | 'new'): number | null {
  const m = new RegExp(`COMMANDS\\(${which}\\) = (\\d+)`).exec(md);
  return m ? Number(m[1]) : null;
}

describe('Phase 2 baseline measurement', () => {
  let oldKb: Assembly;
  let newKb: Assembly;
  let baselineMd: string;

  beforeAll(() => {
    oldKb = assemble(OLD_SCRIPT, 'old');
    newKb = assemble(NEW_SCRIPT, 'new');
    baselineMd = readFileSync(BASELINE_MD, 'utf8');
  }, 600_000);

  afterAll(() => {
    for (const kb of [oldKb, newKb]) if (kb) rmSync(kb.kbDir, { recursive: true, force: true });
  });

  it('assembles a semantically identical KB either way', () => {
    // Not `toBe` on the strings: on a mismatch the parsed diff names the node/claim
    // that drifted, instead of dumping two 40 KB blobs.
    expect(JSON.parse(newKb.snapshot)).toEqual(JSON.parse(oldKb.snapshot));
    expect(newKb.snapshot).toBe(oldKb.snapshot);
  });

  it('costs at most half the commands of the old path', () => {
    expect(newKb.commands).toBeLessThanOrEqual(0.5 * oldKb.commands);
  });

  it('assembles synthesis context only through `node show --context`', () => {
    // Greppable gate (04 §4): the whole point of the new path is that context comes
    // from ONE read per node, so a bare `node show` anywhere in the script would mean
    // context was re-assembled by hand.
    const bare = readFileSync(NEW_SCRIPT, 'utf8')
      .split('\n')
      .filter((line) => !line.trimStart().startsWith('#'))
      .filter((line) => /\bnode show\b/.test(line))
      .filter((line) => !/--context\b/.test(line));
    expect(bare).toEqual([]);
  });

  it('records both measured counts in docs/plans/baseline.md', () => {
    expect(recordedCount(baselineMd, 'old')).toBe(oldKb.commands);
    expect(recordedCount(baselineMd, 'new')).toBe(newKb.commands);
  });

  it('records the current fixture semantic hash in docs/plans/baseline.md', () => {
    const hash = createHash('sha256').update(newKb.snapshot).digest('hex');
    expect(baselineMd).toContain(hash);
  });
});
