import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import type { Repositories } from '../db/repositories/index.js';
import type { Node, Claim, Source, Span, Entity, Relationship } from '../domain/schemas/models.js';
import type { NodeId, ClaimId } from '../domain/ids.js';
import { makeClaimId } from '../domain/ids.js';
import { sha256Hex } from '../domain/algorithms/hash.js';
import { extractCitations } from '../domain/algorithms/citations.js';

/**
 * Deterministic markdown projection of the knowledge base.
 *
 * SQLite is the source of truth; this module renders it to read-only markdown
 * under a `kb/` prefix. {@link renderAll} is PURE and DETERMINISTIC: it reads
 * only the DB (whose repositories already impose stable ORDER BY) and never
 * consults the wall clock or a PRNG, so identical DB state yields byte-identical
 * output. `contentHash` is `sha256Hex(body)`.
 */

/** A single rendered file. `path` is relative to the KB root, e.g. "kb/index.md". */
export interface RenderedFile {
  path: string;
  body: string;
  contentHash: string;
}

const HEADER = '<!-- GENERATED by kb-ingest — do not edit; source of truth is kb.sqlite -->';

/** Build a {@link RenderedFile} from a path + body, computing the content hash. */
function makeFile(path: string, body: string): RenderedFile {
  return { path, body, contentHash: sha256Hex(body) };
}

/** Slug segments from the root down to (and including) `node`. */
function segmentsFor(repos: Repositories, node: Node): string[] {
  const segs: string[] = [];
  let cur: Node | undefined = node;
  while (cur) {
    segs.unshift(cur.slug);
    cur = cur.parentId === null ? undefined : repos.nodes.getById(cur.parentId);
  }
  return segs;
}

/** Relative file path (under `kb/synthesis/`) for a node, with/without children. */
function synthesisPath(segs: string[], hasChildren: boolean): string {
  const joined = segs.join('/');
  return hasChildren ? `kb/synthesis/${joined}/index.md` : `kb/synthesis/${joined}.md`;
}

/**
 * From a parent's `index.md`, a child file path resolves as a sibling link.
 * `index.md` lives at `kb/synthesis/<a>/<b>/index.md`; a leaf child lives at
 * `kb/synthesis/<a>/<b>/<childSlug>.md` and a parent child at
 * `kb/synthesis/<a>/<b>/<childSlug>/index.md`. So the relative link from the
 * parent index is just the child's last segment + suffix.
 */
function childLink(childSlug: string, childHasChildren: boolean): string {
  return childHasChildren ? `${childSlug}/index.md` : `${childSlug}.md`;
}

/** Resolve a claim citation to its footnote definition line (never throws). */
function footnoteDef(repos: Repositories, citation: string): string {
  let claimId: ClaimId;
  try {
    claimId = makeClaimId(citation);
  } catch {
    return `[^${citation}]: (unresolved citation)`;
  }
  const claim: Claim | undefined = repos.claims.getById(claimId);
  if (!claim) return `[^${citation}]: (unresolved citation)`;
  const span: Span | undefined = repos.claimSpans.spansForClaim(claimId)[0];
  if (!span) return `[^${citation}]: (unresolved citation)`;
  const source: Source | undefined = repos.sources.getById(span.sourceId);
  if (!source) return `[^${citation}]: (unresolved citation)`;
  return `[^${citation}]: ${claim.text} — “${span.quote}” (${source.title}, ${source.storedPath})`;
}

/** Footnote-definition block for every citation in `bodyMd`, in first-seen order. */
function sourcesSection(repos: Repositories, bodyMd: string): string {
  const citations = extractCitations(bodyMd);
  if (citations.length === 0) return '';
  const defs = citations.map((c) => footnoteDef(repos, c)).join('\n');
  return `\n\n## Sources\n\n${defs}`;
}

/** Render one synthesis node to a {@link RenderedFile}. */
function renderNode(repos: Repositories, node: Node): RenderedFile {
  const children = repos.nodes.children(node.id);
  const hasChildren = children.length > 0;
  const segs = segmentsFor(repos, node);
  const path = synthesisPath(segs, hasChildren);

  const parts: string[] = [HEADER, '', `# ${node.title}`];
  if (node.bodyMd.length > 0) parts.push('', node.bodyMd);

  if (hasChildren) {
    const lines = children.map((c) => {
      const grandkids = repos.nodes.children(c.id).length > 0;
      const link = childLink(c.slug, grandkids);
      const summary = c.summary.length > 0 ? ` — ${c.summary}` : '';
      return `- [${c.title}](${link})${summary}`;
    });
    parts.push('', '## Subtopics', '', ...lines);
  }

  let body = parts.join('\n');
  body += sourcesSection(repos, node.bodyMd);
  body += '\n';
  return makeFile(path, body);
}

/** Path of the root synthesis file, used by index.md to link the tree. */
function rootSynthesisPath(repos: Repositories): string | undefined {
  const root = repos.nodes.getRoot();
  if (!root) return undefined;
  const hasChildren = repos.nodes.children(root.id).length > 0;
  return synthesisPath(segmentsFor(repos, root), hasChildren);
}

/** kb/index.md — sources registry + entry points. */
function renderIndex(repos: Repositories): RenderedFile {
  const sources: Source[] = repos.sources.listAll();
  const lines: string[] = [HEADER, '', '# Knowledge Base Index', '', '## Sources', ''];
  if (sources.length === 0) {
    lines.push('_No sources ingested._');
  } else {
    lines.push('| Title | Ingested | Source | Status |');
    lines.push('| --- | --- | --- | --- |');
    for (const s of sources) {
      lines.push(`| ${s.title} | ${s.ingestedAt} | [${s.storedPath}](../${s.storedPath}) | ${s.status} |`);
    }
  }

  lines.push('', '## Synthesis', '');
  const rootPath = rootSynthesisPath(repos);
  if (rootPath) {
    const root = repos.nodes.getRoot()!;
    // Link target is relative to kb/index.md; strip the leading "kb/".
    const rel = rootPath.replace(/^kb\//, '');
    lines.push(`- [${root.title}](${rel})`);
  } else {
    lines.push('_No synthesis yet._');
  }

  lines.push('', '## Graph', '');
  lines.push('- [Entities](graph/entities.md)');
  lines.push('- [Relationships](graph/relationships.md)');
  lines.push('', '## Other', '');
  lines.push('- [Changelog](changelog.md)');
  lines.push('- [Open Questions](open-questions.md)');

  return makeFile('kb/index.md', lines.join('\n') + '\n');
}

/** kb/changelog.md — most recent mutations, newest first. */
function renderChangelog(repos: Repositories): RenderedFile {
  const rows = repos.changelog.recent(200); // already ORDER BY id DESC (newest first)
  const lines: string[] = [HEADER, '', '# Changelog', ''];
  if (rows.length === 0) {
    lines.push('_No changes recorded._');
  } else {
    for (const r of rows) {
      lines.push(`- ${r.ts} **${r.op}** — ${r.summary}`);
    }
  }
  return makeFile('kb/changelog.md', lines.join('\n') + '\n');
}

interface ConflictedRow {
  id: string;
  node_id: string | null;
  claim_type: string;
  status: string;
  text: string;
}

/** kb/open-questions.md — unresolved questions and conflicted claims. */
function renderOpenQuestions(repos: Repositories): RenderedFile {
  // No repo method for status filtering; read via the shared connection. Stable
  // order by (created_at, id) mirrors the other claim queries.
  const rows = repos.db
    .prepare(
      `SELECT id, node_id, claim_type, status, text FROM claims
       WHERE status = 'conflicted' OR claim_type = 'open_question'
       ORDER BY created_at, id`,
    )
    .all()
    .map((r) => r as ConflictedRow);

  const lines: string[] = [HEADER, '', '# Open Questions', ''];
  if (rows.length === 0) {
    lines.push('_No open questions._');
    return makeFile('kb/open-questions.md', lines.join('\n') + '\n');
  }

  for (const row of rows) {
    const claimId = makeClaimId(row.id);
    lines.push(`- ${row.text}`);
    lines.push(`  - Type: ${row.claim_type}`);
    lines.push(`  - Status: ${row.status}`);
    if (row.node_id !== null) {
      const node = repos.nodes.getById(row.node_id as NodeId);
      if (node) lines.push(`  - Node: ${node.title}`);
    }
    for (const span of repos.claimSpans.spansForClaim(claimId)) {
      const source = repos.sources.getById(span.sourceId);
      const where = source ? ` (${source.title}, ${source.storedPath})` : '';
      lines.push(`  - “${span.quote}”${where}`);
    }
  }

  return makeFile('kb/open-questions.md', lines.join('\n') + '\n');
}

/** kb/graph/entities.md — entities grouped by type. */
function renderEntities(repos: Repositories): RenderedFile {
  const entities: Entity[] = repos.entities.listAll(); // ORDER BY type, normalized_name
  const lines: string[] = [HEADER, '', '# Entities', ''];
  if (entities.length === 0) {
    lines.push('_No entities._');
    return makeFile('kb/graph/entities.md', lines.join('\n') + '\n');
  }

  let currentType: string | undefined;
  for (const e of entities) {
    if (e.type !== currentType) {
      currentType = e.type;
      lines.push(`## ${e.type}`, '');
    }
    const desc = e.description.length > 0 ? ` — ${e.description}` : '';
    lines.push(`- **${e.canonicalName}** (${e.type})${desc}`);
  }

  return makeFile('kb/graph/entities.md', lines.join('\n') + '\n');
}

/** kb/graph/relationships.md — relationship triples with resolved entity names. */
function renderRelationships(repos: Repositories): RenderedFile {
  const rels: Relationship[] = repos.relationships.listAll(); // ORDER BY type
  const lines: string[] = [HEADER, '', '# Relationships', ''];
  if (rels.length === 0) {
    lines.push('_No relationships._');
    return makeFile('kb/graph/relationships.md', lines.join('\n') + '\n');
  }

  for (const r of rels) {
    const subject = repos.entities.getById(r.subjectEntityId);
    const object = repos.entities.getById(r.objectEntityId);
    const subjName = subject ? subject.canonicalName : r.subjectEntityId;
    const objName = object ? object.canonicalName : r.objectEntityId;
    const desc = r.description.length > 0 ? ` — ${r.description}` : '';
    lines.push(`- ${subjName} **${r.type}** ${objName}${desc}`);
    for (const span of repos.relationshipSpans.spansForRelationship(r.id)) {
      const source = repos.sources.getById(span.sourceId);
      const where = source ? ` (${source.title}, ${source.storedPath})` : '';
      lines.push(`  - “${span.quote}”${where}`);
    }
  }

  return makeFile('kb/graph/relationships.md', lines.join('\n') + '\n');
}

/**
 * Render the entire KB to an array of {@link RenderedFile}. PURE + DETERMINISTIC:
 * no Date/now, no Math.random; all ordering comes from the repositories, which
 * already sort by stable keys. The returned array is itself in a stable order
 * (synthesis nodes by depth/sort_order/id, then the fixed top-level docs).
 */
export function renderAll(repos: Repositories): RenderedFile[] {
  const files: RenderedFile[] = [];

  // Synthesis tree, in nodes.listAll() order (depth, sort_order, id) — stable.
  for (const node of repos.nodes.listAll()) {
    files.push(renderNode(repos, node));
  }

  files.push(renderIndex(repos));
  files.push(renderChangelog(repos));
  files.push(renderOpenQuestions(repos));
  files.push(renderEntities(repos));
  files.push(renderRelationships(repos));

  return files;
}

/** Map a synthesis file path back to its owning node id, if any (for bookkeeping). */
function nodeIdForPath(repos: Repositories, path: string): NodeId | null {
  if (!path.startsWith('kb/synthesis/')) return null;
  for (const node of repos.nodes.listAll()) {
    const hasChildren = repos.nodes.children(node.id).length > 0;
    if (synthesisPath(segmentsFor(repos, node), hasChildren) === path) return node.id;
  }
  return null;
}

/**
 * Write every rendered file under `<root>/<path>` (creating directories), then
 * record it in `rendered_files`. `now` is injected (the only timestamp; render
 * bodies carry none) so callers control bookkeeping time.
 */
export function writeRender(
  root: string,
  files: RenderedFile[],
  repos: Repositories,
  now: string,
): { written: number } {
  let written = 0;
  for (const file of files) {
    const abs = join(root, file.path);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, file.body);
    repos.renderedFiles.upsert(file.path, nodeIdForPath(repos, file.path), file.contentHash, now);
    written++;
  }
  return { written };
}

/**
 * Compare each expected file against what is on disk under `<root>`:
 *  - 'missing'  — the file does not exist on disk,
 *  - 'drifted'  — it exists but its bytes differ from the expected body,
 *  - 'ok'       — it exists and matches.
 */
export function checkRender(
  root: string,
  files: RenderedFile[],
): Array<{ path: string; status: 'ok' | 'missing' | 'drifted' }> {
  return files.map((file) => {
    const abs = join(root, file.path);
    if (!existsSync(abs)) return { path: file.path, status: 'missing' as const };
    const onDisk = readFileSync(abs, 'utf8');
    return { path: file.path, status: onDisk === file.body ? ('ok' as const) : ('drifted' as const) };
  });
}
