#!/usr/bin/env bash
#
# gen-baseline.sh — (re)generate docs/plans/baseline.md from actual runs of BOTH
# baseline scripts. Records each script's command count, the run date, and the semantic
# fixture hash (sha256 of the normalized kb-snapshot of the assembled KB).
#
# It also enforces the two Phase 2 gates (04 §4) before writing, so the recorded numbers
# can never describe a run that failed them:
#   1. equivalence — the two KBs produce byte-identical kb-snapshot output
#      (raw DB bytes legitimately differ: timestamps, changelog, write order);
#   2. cost        — COMMANDS(new) ≤ 0.5 × COMMANDS(old).
#
# baseline.md is GENERATED — do not hand-edit; run this instead. src/cli/baseline.test.ts
# re-measures both scripts and fails if the recorded figures have drifted.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
TSX="$ROOT/node_modules/.bin/tsx"
OUT="$ROOT/docs/plans/baseline.md"

OLDKB="$(mktemp -d "${TMPDIR:-/tmp}/kb-baseline-old.XXXXXX")"
NEWKB="$(mktemp -d "${TMPDIR:-/tmp}/kb-baseline-new.XXXXXX")"
OLDSNAP="$(mktemp "${TMPDIR:-/tmp}/kb-snapshot-old.XXXXXX")"
NEWSNAP="$(mktemp "${TMPDIR:-/tmp}/kb-snapshot-new.XXXXXX")"
trap 'rm -rf "$OLDKB" "$NEWKB" "$OLDSNAP" "$NEWSNAP"' EXIT

COMMANDS_OLD="$(bash "$ROOT/scripts/baseline-old.sh" "$OLDKB" | sed -n 's/^COMMANDS=//p')"
COMMANDS_NEW="$(bash "$ROOT/scripts/baseline-new.sh" "$NEWKB" | sed -n 's/^COMMANDS=//p')"

"$TSX" "$ROOT/scripts/kb-snapshot.ts" "$OLDKB" > "$OLDSNAP"
"$TSX" "$ROOT/scripts/kb-snapshot.ts" "$NEWKB" > "$NEWSNAP"
if ! diff -u "$OLDSNAP" "$NEWSNAP"; then
  echo "gen-baseline: FAIL — the two scripts assemble semantically different KBs (diff above)" >&2
  exit 1
fi

HALF=$(( COMMANDS_OLD / 2 ))
if (( COMMANDS_NEW > HALF )); then
  echo "gen-baseline: FAIL — COMMANDS(new)=${COMMANDS_NEW} exceeds 0.5 × COMMANDS(old)=${COMMANDS_OLD} (limit ${HALF})" >&2
  exit 1
fi

HASH="$(shasum -a 256 < "$NEWSNAP" | cut -d' ' -f1)"
PERCENT="$(node -e "process.stdout.write((100 * $COMMANDS_NEW / $COMMANDS_OLD).toFixed(1))")"
RUN_DATE="$(date +%Y-%m-%d)"

cat > "$OUT" <<EOF
# Baseline — orchestration cost

Generated by \`scripts/gen-baseline.sh\` (do not hand-edit). Re-run after any change
to the fixture corpus or to either assembly path.

- **Date measured:** ${RUN_DATE}
- **Fixture semantic hash:** \`${HASH}\`
  (sha256 of \`scripts/kb-snapshot.ts\` output — the normalized semantic snapshot,
  excluding timestamps/changelog/render bookkeeping; identical for both scripts)

## Old-script command count

\`scripts/baseline-old.sh\` assembles the fixture KB with Phase-0 commands only and
counts every \`kb\` invocation:

- **COMMANDS(old) = ${COMMANDS_OLD}**

Breakdown: \`init\` ×1, \`ingest\` ×4, \`node create\` ×21, \`claim apply\` ×3,
\`graph apply\` ×1, \`synthesize\` ×21, \`verify --strict\` ×1, \`render\` ×1,
\`render --check\` ×1.

## New-script command count

\`scripts/baseline-new.sh\` assembles the SAME KB with the Phase-2 batching commands,
counting every \`kb\` invocation the same way:

- **COMMANDS(new) = ${COMMANDS_NEW}**

Breakdown: \`init\` ×1, \`ingest\` ×4, \`node apply\` ×1, \`claim apply\` ×3,
\`graph apply\` ×1, \`node show --context\` ×6, \`synthesize\` (batch) ×3,
\`verify --strict\` ×1, \`render\` ×1, \`render --check\` ×1.

The six \`--context\` reads are the synthesis prep the new path pays for — one read of
the root subtree for the leaf batch, one per topic once its leaves carry fresh
summaries, and one of the root for the root batch. They are counted like every other
invocation, and they are the ONLY context assembly in the script (04 §4).

## Result (04 §4)

| | old | new |
|---|---|---|
| commands | ${COMMANDS_OLD} | ${COMMANDS_NEW} |

- **COMMANDS(new) ≤ 0.5 × COMMANDS(old)**: ${COMMANDS_NEW} ≤ ${HALF} ✓ (${PERCENT} % of the old cost)
- **Semantic equivalence**: \`scripts/kb-snapshot.ts\` output is byte-identical for both
  KBs ✓ (raw DB bytes are *expected* to differ — timestamps, changelog, write order)

Both gates are enforced by this generator before it writes, and re-measured by
\`src/cli/baseline.test.ts\`.
EOF

echo "wrote $OUT (old=$COMMANDS_OLD, new=$COMMANDS_NEW, hash=$HASH)"
